services:
  # Thrive UI
  thrive-ui:
    build:
      context: ./UI/ThriveChurchMediaToolUI
      dockerfile: Dockerfile
    image: thrive-media-tool-ui:latest
    container_name: thrive-ui
    ports:
      - "8081:80"
    restart: unless-stopped

