version: '3.8'

services:
  # Thrive UI
  ui:
    build:
      context: ./UI/ThriveChurchMediaToolUI
      dockerfile: Dockerfile
    container_name: thrive-ui
    ports:
      - "8081:80"
    restart: unless-stopped

